var ComponentList = []

ComponentList.push({name:'Stroop Color', iconFileName:'StroopColor.png'})
ComponentList.push({name:'Stroop Word', iconFileName:'StroopWord.png'})
ComponentList.push({name:'Stroop Color/Word', iconFileName:'StroopColorWord.png'})
ComponentList.push({name:'Trail Making', iconFileName:'TrailMaking.png'})
ComponentList.push({name:'Word Recall', iconFileName:'WordRecall.png'})
ComponentList.push({name:'Matrix Reasoning', iconFileName:'MatrixReasoning.png'})
ComponentList.push({name:'Card Sort', iconFileName: 'CardSort.png'})
ComponentList.push({name:'Image Copy', iconFileName:'ShapeCopy.png'})
ComponentList.push({name:'Likert', iconFileName:'Likert.png'})
ComponentList.push({name:'MultipleChoice', iconFileName:'MultiChoice.png'})
ComponentList.push({name:'Digit Span', iconFileName:'DigitSpan.png'})
ComponentList.push({name:'Serial Subtraction', iconFileName:'SerialSubtraction.png'})
ComponentList.push({name:'Fluency', iconFileName:'Fluency.png'})
ComponentList.push({name:'Line Bisection', iconFileName:'LineBisection.png'})
ComponentList.push({name:'Clock Drawing', iconFileName:'ClockDrawing.png'})
ComponentList.push({name:'Verbal DMS', iconFileName:'VerbalDMS.png'})
ComponentList.push({name:'Cancellation Task', iconFileName:'Cancellation.png'})
ComponentList.push({name:'Spatial DMS', iconFileName:'SpatialDMS.png'})
ComponentList.push({name:'Listening', iconFileName: 'Listening.png'})
ComponentList.push({name:'Intake Form', iconFileName:'MultiChoice.png'})
ComponentList.push({name:'Screening', iconFileName:'Screening.png'})
ComponentList.push({name:'Word Recognition', iconFileName:'WordRecog.png'})
ComponentList.push({name:'Consent Form', iconFileName:'ConsentForm.png'})
ComponentList.push({name:'Reading Test', iconFileName:'ReadingTest.png'})
ComponentList.push({name:'Questionnaire', iconFileName:'MultiChoice.png'})
ComponentList.push({name:'Pattern Comparison', iconFileName:'PatternComparison.png'})
ComponentList.push({name:'Screening', iconFileName:'Screening.png'})
ComponentList.push({name:'Email Entry', iconFileName:'MultiChoice.png'})