#!/usr/bin/env node
// Turns the JSON produced by extract.js into SQL INSERT statements for
// task_parameters / task_instructions, plus a manual-review report for
// everything that can't be placed automatically.
//
// Usage: node extract.js && node generate_sql.js
// Output: Migrated_TaskConfig.sql, MANUAL_REVIEW.md (both in this folder)

'use strict';
const fs = require('fs');
const path = require('path');

const EXTRACTED_DIR = path.join(__dirname, 'extracted');
const SQL_OUT = path.join(__dirname, 'Migrated_TaskConfig.sql');
const REVIEW_OUT = path.join(__dirname, 'MANUAL_REVIEW.md');

// Basename (without _Setup.js / _setup.js / _Instructions.js) -> task_types.task_name.
// Built by comparing config/InstructionsAndStimuli filenames against the 27 rows
// SeedData_TaskTypes.sql currently defines. Files with no entry here have no
// matching task_types row yet (see MANUAL_REVIEW.md) and are not migrated.
const TASK_NAME_BY_BASENAME = {
  CardSort: 'Card Sort',
  CardSortTask: 'Card Sort',
  ClockDrawing: 'Clock Drawing',
  ConsentForm: 'Consent Form',
  DigitSpan: 'Digit Span',
  EndingPage: 'Ending Page',
  Fluency: 'Fluency',
  IntakeForm: 'Intake Form',
  LanguageSelection: 'Language Selection',
  LineBisection: 'Line Bisection',
  Listening: 'Listening',
  MatrixReasoning: 'Matrix Reasoning',
  PatternComparison: 'Pattern Comparison',
  Questionnaire: 'Questionnaire',
  Screening: 'Screening',
  SerialSubtraction: 'Serial Subtraction',
  SpatialDMS: 'Spatial DMS',
  TrailMaking: 'Trail Making',
  VASrating: 'VAS Rating',
  WordRecall: 'Word Recall',
  WordRecog: 'Word Recognition',
  YesNo: 'Yes No',
  vDMS: 'Verbal DMS', // medium confidence -- confirm "vDMS" means Verbal DMS, not a second spatial variant
};

// Registrations that are legitimately not task_parameters rows at all --
// they belong to shared/global config, not to any one task_type. Excluded
// from SQL generation and called out in the report instead of silently
// dropped or wrongly inserted.
const NON_TASK_FILES = new Set(['General_Setup.js', 'SessionChooser_config.js', 'Button_config.js']);

function sqlEscape(str) {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "''");
}

function loadExtracted() {
  return fs
    .readdirSync(EXTRACTED_DIR)
    .filter((f) => f.startsWith('parameters__') || f.startsWith('instructions__'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(EXTRACTED_DIR, f), 'utf8')));
}

function baseName(filePath) {
  return path.basename(filePath).replace(/_(Setup|setup|Instructions|config)\.js$/, '');
}

function main() {
  const files = loadExtracted();
  const sqlLines = [
    '-- Auto-generated by migrate/generate_sql.js -- DO NOT hand-edit, regenerate instead.',
    '-- Source: config/*.js and InstructionsAndStimuli/Instructions/*.js, extracted via extract.js.',
    'USE ncmbattery_config;',
    '',
  ];
  const unmappedFiles = []; // whole files with no task_types match
  const skippedNonTask = []; // registrations from shared/global files
  const sourceErrors = []; // genuine bugs found in the existing .js source
  let insertCount = 0;

  for (const result of files) {
    const fname = path.basename(result.file);
    const base = baseName(result.file);
    const taskName = TASK_NAME_BY_BASENAME[base];

    for (const reg of result.registrations || []) {
      if (reg.error) {
        sourceErrors.push({ file: fname, key: reg.key, error: reg.error });
        continue;
      }
      if (reg.isTimelineTrial) {
        skippedNonTask.push({ file: fname, key: reg.key, reason: 'pushes a jsPsych trial fragment onto the shared timeline, not a task_parameters object' });
        continue;
      }
      if (NON_TASK_FILES.has(fname)) {
        skippedNonTask.push({ file: fname, key: reg.key, reason: `${fname} defines shared/global config, not a single task's parameters` });
        continue;
      }
      if (!taskName) {
        if (!unmappedFiles.includes(fname)) unmappedFiles.push(fname);
        continue;
      }

      const lang = reg.language || 'EN';
      const json = sqlEscape(reg.json);
      const nameCol = sqlEscape(reg.key);
      const taskNameEsc = sqlEscape(taskName);

      if (result.kind === 'parameters') {
        sqlLines.push(
          `INSERT IGNORE INTO task_parameters (task_type_id, parameter_name, language, parameters_json)`,
          `SELECT task_type_id, '${nameCol}', '${lang}', '${json}'`,
          `FROM task_types WHERE task_name = '${taskNameEsc}';`,
          ''
        );
      } else {
        sqlLines.push(
          `INSERT IGNORE INTO task_instructions (task_type_id, instruction_name, language, instructions_json)`,
          `SELECT task_type_id, '${nameCol}', '${lang}', '${json}'`,
          `FROM task_types WHERE task_name = '${taskNameEsc}';`,
          ''
        );
      }
      insertCount++;
    }
  }

  fs.writeFileSync(SQL_OUT, sqlLines.join('\n'));

  const review = [
    '# Migration: Manual Review',
    '',
    `Generated by \`generate_sql.js\`. ${insertCount} INSERT statements were written to \`Migrated_TaskConfig.sql\`.`,
    '',
    '## Files with no matching task_types row',
    '',
    'These config/instructions files have registrations that were extracted cleanly, but there is',
    'no row in `task_types` to attach them to yet. Either the task type needs to be added to',
    '`SeedData_TaskTypes.sql` (with its HTML file), or the task is deprecated/unused and these',
    'files can be left out of the migration.',
    '',
    unmappedFiles.length ? unmappedFiles.map((f) => `- ${f}`).join('\n') : '_none_',
    '',
    '## Registrations excluded as non-task-specific',
    '',
    'These are real, cleanly-extracted values, but they are shared/global config or jsPsych',
    'timeline fragments rather than one task\'s parameter/instruction set, so they do not belong',
    'in `task_parameters`/`task_instructions` as currently designed. Needs a design decision on',
    'where they should live (e.g. a `ui_labels` table for LabelNames, or leaving them as JS).',
    '',
    skippedNonTask.length
      ? skippedNonTask.map((r) => `- **${r.file}** \`${r.key}\` — ${r.reason}`).join('\n')
      : '_none_',
    '',
    '## Pre-existing bugs found in the source (not caused by migration)',
    '',
    'Each of these calls `add(\'key\', ...)` with a callback that references a variable never',
    'defined anywhere in the file. These are dead/broken registrations in the *current* codebase —',
    'pseudoSwitch(key) would throw a ReferenceError at runtime today if anything ever selected them.',
    '',
    sourceErrors.length
      ? sourceErrors.map((e) => `- **${e.file}** \`${e.key}\` — ${e.error}`).join('\n')
      : '_none_',
    '',
  ];
  fs.writeFileSync(REVIEW_OUT, review.join('\n'));

  console.log(`Wrote ${insertCount} INSERT statements to ${path.relative(process.cwd(), SQL_OUT)}`);
  console.log(`${unmappedFiles.length} files unmapped, ${skippedNonTask.length} registrations excluded as non-task, ${sourceErrors.length} pre-existing source bugs.`);
  console.log(`See ${path.relative(process.cwd(), REVIEW_OUT)} for details.`);
}

main();
