#!/usr/bin/env node
// Turns every ../schemas/*.json file into an UPDATE of task_types.parameter_schema for each
// task type listed in the file's "taskTypes" (several task types can share one config file,
// e.g. the six questionnaire pages all use Questionnaire_Setup.js).
//
// The stored value is { reviewed, schema, uiSchema } -- what the admin site needs to render
// the form. Editing a schema file and re-running this replaces the stored copy.
//
// Usage: node load_schemas.js
// Output: Load_ParameterSchemas.sql (run after AddParameterSchemaColumn.sql)

'use strict';
const fs = require('fs');
const path = require('path');

const SCHEMA_DIR = path.join(__dirname, '..', 'schemas');
const SQL_OUT = path.join(__dirname, 'Load_ParameterSchemas.sql');

const sql = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;

const out = [
  '-- Auto-generated by migrate/load_schemas.js from schemas/*.json -- DO NOT hand-edit, regenerate instead.',
  '-- Load with: mysql --default-character-set=utf8mb4 ...',
  'USE ncmbattery_config;',
  '',
];
let updates = 0;
for (const f of fs.readdirSync(SCHEMA_DIR).filter((x) => x.endsWith('.json')).sort()) {
  const file = JSON.parse(fs.readFileSync(path.join(SCHEMA_DIR, f), 'utf8'));
  if (!Array.isArray(file.taskTypes) || !file.schema) throw new Error(`${f}: needs "taskTypes" and "schema"`);
  const stored = JSON.stringify({ reviewed: !!file.reviewed, schema: file.schema, uiSchema: file.uiSchema || {} });
  out.push(
    `-- ${f}${file.reviewed ? '' : ' (DRAFT, not yet reviewed)'}`,
    `UPDATE task_types SET parameter_schema = ${sql(stored)}`,
    `WHERE task_name IN (${file.taskTypes.map(sql).join(', ')});`,
    ''
  );
  updates += file.taskTypes.length;
  console.log(`${f}: ${file.taskTypes.join(', ')}${file.reviewed ? '' : ' (draft)'}`);
}
fs.writeFileSync(SQL_OUT, out.join('\n'));
console.log(`Wrote ${SQL_OUT} (${updates} task types).`);
