var FeedbackLength = 400; // This is in milliseconds
var FeedbackFontSize = "30px";
var GapBetweenButtons = "0px";

var FullScreenMode = false;
var TextFontSize = "30px";
var StimulusFontSize = '60px';
// 200 is 5 frames per second
var GIFsetDelay = 250; // 	 Sets the delay time between each frame, or changes it for subsequent frames



var WelcomeTime = 4000; // milliseconds

var SaveLocalFile = false

var EN_LabelNames = {}
EN_LabelNames.NoYes = ['No','Yes']
EN_LabelNames.YesNo = ['Yes','No']
EN_LabelNames.Home = 'Home'
EN_LabelNames.Restart = 'Restart'
EN_LabelNames.Info = 'Info'
EN_LabelNames.Stop = 'Stop'
EN_LabelNames.Quit = 'Quit'
EN_LabelNames.Skip = 'Skip'
EN_LabelNames.Finished = 'Finished'
EN_LabelNames.ProcessSpeech = 'Processing Speech'
EN_LabelNames.Clear = 'Clear'
EN_LabelNames.Undo = 'Undo'
EN_LabelNames.Redo = 'Redo'
EN_LabelNames.Repeat = 'Repeat'
EN_LabelNames.Next = 'Next'
EN_LabelNames.Continue = 'Continue'
EN_LabelNames.Previous = 'Previous'
EN_LabelNames.Enter = 'Enter'
EN_LabelNames.Submit = 'Submit'
EN_LabelNames.Done = 'Done'
EN_LabelNames.CurrentAnswer = 'Current Answer'
EN_LabelNames.Correct = 'Correct'
EN_LabelNames.Incorrect = 'Incorrect'
EN_LabelNames.Same = 'Same'
EN_LabelNames.Different = 'Different'
EN_LabelNames.PressNext = 'Press Next to Continue'
EN_LabelNames.WordListA = 'List A'
EN_LabelNames.WordListB = 'List B'
EN_LabelNames.ProgressBar = 'Completion Progress'
EN_LabelNames.PleaseRead = 'Please read the following sentence out loud'
EN_LabelNames.SelectMicrophone = '<p>Please select the microphone you would like to use.</p>'
EN_LabelNames.UseThisMicrophone = 'Use this microphone.'
EN_LabelNames.NoteInputBox = "Please, type in any notes or feedback you have about this task. (Optional)"
EN_LabelNames.NonEligible = ("I am sorry to say that you are not eligible for this study.")
EN_LabelNames.BroswerNonEligible = ("You are eligible, but our software does not work on mobile. Please try again using a laptop or tablet.")
EN_LabelNames.StopStudy = "This will stop the study but not remove your data. Are you sure?"
EN_LabelNames.ExitStudy = 'This will remove all data collected so far. Are you sure?'
EN_LabelNames.SkipTask = "This will SKIP the current task. Are you sure?"
EN_LabelNames.missed_question_label = "Please select an item"
EN_LabelNames.missed_question_text = "Please answer all questions"
EN_LabelNames.ThankYou = "Thank you for your participation. You may close this window."
EN_LabelNames.Hello = 'Hello'
EN_LabelNames.EnterName = 'Please enter a name first.'
EN_LabelNames.TrailMakingRemaining = 'remaining'

var FR_LabelNames = {}
FR_LabelNames.NoYes = ['No','Oui']
FR_LabelNames.YesNo = ['Oui', 'No']
FR_LabelNames.Home = "Page d'accueil"
FR_LabelNames.Restart = 'Recommencer'
FR_LabelNames.Stop = 'Arrêt'
FR_LabelNames.Quit = 'Quitter'
FR_LabelNames.Skip = 'Passer'
FR_LabelNames.Finished = 'Terminé'
FR_LabelNames.ProcessSpeech = 'Traitement de la parole'
FR_LabelNames.Clear = 'Effacer'
FR_LabelNames.Undo = 'Défaire'
FR_LabelNames.Redo = 'Refaire'
FR_LabelNames.Repeat = 'Répéter'
FR_LabelNames.Next = 'Suivant'
FR_LabelNames.Continue = 'Continuer'
FR_LabelNames.Previous = 'Précédent'
FR_LabelNames.Enter = 'Entrer'
FR_LabelNames.Submit = 'Soumettre'
FR_LabelNames.Done = 'Fini'
FR_LabelNames.CurrentAnswer = 'Réponse Actuelle'
FR_LabelNames.Correct = 'Correct'
FR_LabelNames.Incorrect = 'Incorrect'
FR_LabelNames.Same = 'Mêmes'
FR_LabelNames.Different = 'Différent'
FR_LabelNames.PressNext = 'Appuyez sur Suivant pour continuer'
FR_LabelNames.WordListA = 'Liste A'
FR_LabelNames.WordListB = 'Liste B'
FR_LabelNames.ProgressBar = 'Progrès'
FR_LabelNames.PleaseRead = 'Veuillez lire la phrase suivante à haute voix.'
FR_LabelNames.SelectMicrophone = '<p>Veuillez sélectionner le microphone que vous souhaitez utiliser.</p>'
FR_LabelNames.UseThisMicrophone = 'Utilisez ce micro.'
FR_LabelNames.ProgressBar = 'Progrès'
FR_LabelNames.NoteInputBox = "Veuillez saisir toutes les notes ou commentaires que vous avez sur cette tâche. (Facultatif)"
FR_LabelNames.NonEligible = "Je suis désolé de vous annoncer que vous n'êtes pas éligible pour cette étude."
FR_LabelNames.BroswerNonEligible = "You are eligible, but our software does not work on mobile. Please try again using a laptop or tablet."
FR_LabelNames.StopStudy = "Cela arrêtera l\'étude mais ne supprimera pas vos données. Êtes-vous sûr?"
FR_LabelNames.ExitStudy = "Cela supprimera toutes les données collectées jusqu'à présent. Êtes-vous sûr?"
FR_LabelNames.SkipTask = "Cela va SAUTER la tâche en cours. Etes-vous sûr?"
FR_LabelNames.missed_question_label = "Veuillez sélectionner un article"
FR_LabelNames.missed_question_text = "Veuillez répondre à toutes les questions"
FR_LabelNames.ThankYou = "Merci pour votre participation. Vous pouvez fermer cette fenêtre."
FR_LabelNames.Hello = 'Bonjour'
FR_LabelNames.EnterName = 'Veuillez d\'abord entrer un nom.'
FR_LabelNames.TrailMakingRemaining = 'restantes'


var KR_LabelNames = {}
KR_LabelNames.NoYes = ['아니요','예']
KR_LabelNames.YesNo = ['예','아니요']
KR_LabelNames.Home = '홈페이지'
KR_LabelNames.Restart = '다시 시작하다'
KR_LabelNames.Stop = '멈추다'
KR_LabelNames.Quit = '그만두다'
KR_LabelNames.Skip = 'Skip'
KR_LabelNames.Finished = '완전한'
KR_LabelNames.ProcessSpeech = 'Processing Speech'
KR_LabelNames.Clear = 'Clear'
KR_LabelNames.Undo = 'Undo'
KR_LabelNames.Redo = 'Redo'
KR_LabelNames.Repeat = 'Repeat'
KR_LabelNames.Next = '다음' 
KR_LabelNames.Continue = '계속하다'
KR_LabelNames.Previous = 'Previous'
KR_LabelNames.Enter = '입력하다'
KR_LabelNames.Submit = '제출하다'
KR_LabelNames.Done = '완료'
KR_LabelNames.CurrentAnswer = 'Current Answer'
KR_LabelNames.Correct = '옳은'
KR_LabelNames.Incorrect = '잘못된'
KR_LabelNames.Same = 'Same'
KR_LabelNames.DifferKRt = 'Different'
KR_LabelNames.PressNext = '계속하려면 다음을 클릭하세요'
KR_LabelNames.WordListA = 'List A'
KR_LabelNames.WordListB = 'List B'
KR_LabelNames.ProgressBar = 'Completion Progress'
KR_LabelNames.PleaseRead = 'Please read the following sentence out loud'
KR_LabelNames.SelectMicrophone = '<p>Please select the microphone you would like to use.</p>'
KR_LabelNames.UseThisMicrophone = 'Use this microphone.'
KR_LabelNames.NoteInputBox = "Please, type in any notes or feedback you have about this task. (Optional)"
KR_LabelNames.NonEligible = ("I am sorry to say that you are not eligible for this study.")
KR_LabelNames.BroswerNonEligible = ("You are eligible, but our software does not work on mobile. Please try again using a laptop or tablet.")
KR_LabelNames.StopStudy = "This will stop the study but not remove your data. Are you sure?"
KR_LabelNames.ExitStudy = 'This will remove all data collected so far. Are you sure?'
KR_LabelNames.SkipTask = "This will SKIP the current task. Are you sure?"
KR_LabelNames.missed_question_label = "항목을 선택해 주세요."
KR_LabelNames.missed_question_text = "모든 질문에 답변해 주세요."
KR_LabelNames.ThankYou = "참여해 주셔서 감사합니다. 이 창을 닫아도 됩니다."
KR_LabelNames.Hello = '안녕하세요'
KR_LabelNames.EnterName = '먼저 이름을 입력하세요.'
KR_LabelNames.TrailMakingRemaining = '남음'

add('EN_LabelNames', function(){ LabelNames = EN_LabelNames});
add('FR_LabelNames', function(){ LabelNames = FR_LabelNames});
add('KR_LabelNames', function(){ LabelNames = KR_LabelNames});